CREATE TABLE NETFLIX_OTT_SUBSCRIBERS_REVENUE (Date date, GLOBAL_REVENUE bigint, 
											  UCAN_STREAMING_REVENUE bigint, 
											  EMEA_STREAMING_REVENUE bigint, 
											  LATM_STREAMING_REVENUE Bigint,
											  APAC_STREAMING_REVENUE bigint, 
											  UCAN_MEMBERS bigint, 
											  EMEA_MEMBERS bigint,
											  LATM_MEMBERS bigint, 
											  APAC_MEMBERS bigint, 
											  UCAN_ARPU float, 
											  EMEA_ARPU float, 
											  LATM_ARPU float,
											  APAC_ARPU float, 
											  NETFLIX_STREAMING_MEMBERSHIPS bigint);