/**********     Data Analysis     **********/


-- Fetch the data from netflix_ott_subscribers_revenue.

SELECT *
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the quarter,year from netflix_ott_subscribers_revenue.

SELECT QUARTER,YEAR
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the US Canada members. Find the highest number of members subscribed in which year & quarter. 

SELECT US_CANADA_MEMBERS,YEAR,QUARTER,
       FIRST_VALUE(US_CANADA_MEMBERS) OVER (PARTITION BY YEAR 
	   ORDER BY US_CANADA_MEMBERS DESC) AS HIGHEST_MEMBERS_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Europe Africa members. Find the highest number of members subscribed in which year & quarter.

SELECT EUROPE_AFRICA_MEMBERS,YEAR,QUARTER,
	   FIRST_VALUE(EUROPE_AFRICA_MEMBERS) OVER (PARTITION BY YEAR
       ORDER BY EUROPE_AFRICA_MEMBERS DESC) AS HIGHEST_MEMBERS_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Latin America members. Find the highest number of members subscribed in which year & quarter.

SELECT LATIN_AMERICA_MEMBERS,YEAR,QUARTER,
	   FIRST_VALUE(LATIN_AMERICA_MEMBERS) OVER (PARTITION BY YEAR
       ORDER BY LATIN_AMERICA_MEMBERS DESC) AS HIGHEST_MEMBERS_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Asia pacific members. Find the highest number of members subscribed in which year & quarter.

SELECT ASIA_PACIFIC_MEMBERS,YEAR,QUARTER,
	   FIRST_VALUE(ASIA_PACIFIC_MEMBERS) OVER (PARTITION BY YEAR
       ORDER BY ASIA_PACIFIC_MEMBERS DESC) AS HIGHEST_MEMBERS_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Netflix streaming membership. Find the year with the highest number of subscribers.

SELECT YEAR,
	SUM(NETFLIX_STREAMING_MEMBERSHIPS) AS HIGHEST_MEMBERS_IN_YEAR
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE
GROUP BY YEAR
ORDER BY HIGHEST_MEMBERS_IN_YEAR DESC;

-- Fetch the US Canada ARPU. Find the highest ARPU in which year & quarter.

SELECT US_CANADA_AVG_REVENUE_PER_USER,YEAR,QUARTER,
	   FIRST_VALUE(US_CANADA_AVG_REVENUE_PER_USER) OVER (PARTITION BY YEAR
       ORDER BY US_CANADA_AVG_REVENUE_PER_USER DESC) AS HIGHEST_ARPU_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Europe Africa ARPU. Find the highest ARPU in which year & quarter.

SELECT EUROPE_AFRICA_AVG_REVENUE_PER_USER,YEAR,QUARTER,
	   FIRST_VALUE(EUROPE_AFRICA_AVG_REVENUE_PER_USER) OVER (PARTITION BY YEAR
       ORDER BY EUROPE_AFRICA_AVG_REVENUE_PER_USER DESC) AS HIGHEST_ARPU_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Latin America ARPU. Find the highest ARPU in which year & quarter.

SELECT LATIN_AMERICA_AVG_REVENUE_PER_USER,YEAR,QUARTER,
	   FIRST_VALUE(LATIN_AMERICA_AVG_REVENUE_PER_USER) OVER (PARTITION BY YEAR
       ORDER BY LATIN_AMERICA_AVG_REVENUE_PER_USER DESC) AS HIGHEST_ARPU_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Asia Pacific ARPU. Find the highest ARPU in which year & quarter.

SELECT ASIA_PACIFIC_AVG_REVENUE_PER_USER,YEAR,QUARTER,
	   FIRST_VALUE(ASIA_PACIFIC_AVG_REVENUE_PER_USER) OVER (PARTITION BY YEAR
       ORDER BY ASIA_PACIFIC_AVG_REVENUE_PER_USER DESC) AS HIGHEST_ARPU_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE; 

-- Fetch the US Canada streaming revenue. Find the highest revenue in which year & quarter.

SELECT US_CANADA_STREAMING_REVENUE,YEAR,QUARTER,
	   FIRST_VALUE(US_CANADA_STREAMING_REVENUE) OVER (PARTITION BY YEAR
       ORDER BY US_CANADA_STREAMING_REVENUE DESC) AS HIGHEST_REVENUE_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- In which year the top revenue generated in US Canada. 

SELECT YEAR,SUM(US_CANADA_STREAMING_REVENUE) AS TOTAL_REVENUE_IN_YEAR
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE
GROUP BY YEAR
ORDER BY TOTAL_REVENUE_IN_YEAR DESC
LIMIT 1;

-- Fetch the Europe Africa streaming revenue. Find the highest revenue in which year & quarter.

SELECT EUROPE_AFRICA_STREAMING_REVENUE,YEAR,QUARTER,
	   FIRST_VALUE(EUROPE_AFRICA_STREAMING_REVENUE) OVER (PARTITION BY YEAR
       ORDER BY EUROPE_AFRICA_STREAMING_REVENUE DESC) AS HIGHEST_REVENUE_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Latin America streaming revenue. Find the highest revenue in which year & quarter.

SELECT LATIN_AMERICA_STREAMING_REVENUE,YEAR,QUARTER,
	   FIRST_VALUE(LATIN_AMERICA_STREAMING_REVENUE) OVER (PARTITION BY YEAR
       ORDER BY LATIN_AMERICA_STREAMING_REVENUE DESC) AS HIGHEST_REVENUE_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the Asia Pacific streaming revenue. Find the highest revenue in which year & quarter.

SELECT ASIA_PACIFIC_STREAMING_REVENUE,YEAR,QUARTER,
	   FIRST_VALUE(ASIA_PACIFIC_STREAMING_REVENUE) OVER (PARTITION BY YEAR
       ORDER BY ASIA_PACIFIC_STREAMING_REVENUE DESC) AS HIGHEST_REVENUE_IN_QUARTER
FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE;

-- Fetch the global revenue for all four Regions and determine the year with the highest total global revenue and rank the revenue. 

SELECT X.YEAR,
	   TOTAL_REVENUE_OF_YEAR,
	   RANK() OVER (ORDER BY TOTAL_REVENUE_OF_YEAR DESC) AS REVENUE_RANK
FROM
	(
	   SELECT YEAR,
	   SUM(GLOBAL_REVENUE_USD) AS TOTAL_REVENUE_OF_YEAR
	   FROM NETFLIX_OTT_SUBSCRIBERS_REVENUE
	   GROUP BY YEAR
	) X;